doctrine:
    dbal:
        default_connection: order
        connections:
            order:
                url: '%env(resolve:DATABASE_ORDER_URL)%'
                server_version: '16'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            invoice:
                url: '%env(resolve:DATABASE_INVOICE_URL)%'
                server_version: '16'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true

        types:
            order_id: App\Order\Infrastructure\Persistence\Doctrine\Types\OrderIdType
            product_id: App\Order\Infrastructure\Persistence\Doctrine\Types\ProductIdType
            customer_id: App\Order\Infrastructure\Persistence\Doctrine\Types\CustomerIdType
            seller_id: App\Order\Infrastructure\Persistence\Doctrine\Types\SellerIdType
            order_status: App\Order\Infrastructure\Persistence\Doctrine\Types\OrderStatusType
            price: App\Order\Infrastructure\Persistence\Doctrine\Types\PriceType
            quantity: App\Order\Infrastructure\Persistence\Doctrine\Types\QuantityType
            invoice_id: App\Invoice\Infrastructure\Persistence\Doctrine\Types\InvoiceIdType
            file_path: App\Invoice\Infrastructure\Persistence\Doctrine\Types\FilePathType
            sent_at: App\Invoice\Infrastructure\Persistence\Doctrine\Types\SentAtType

    orm:
        default_entity_manager: order
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        entity_managers:
            order:
                connection: order
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Order:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Order/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Order\Domain\Entity'
                        alias: Order
            invoice:
                connection: invoice
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Invoice:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Invoice/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Invoice\Domain\Entity'
                        alias: Invoice

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
