table_storage:
    table_name: doctrine_migration_versions_invoice
    version_column_name: version
    version_column_length: 1024
    executed_at_column_name: executed_at
    execution_time_column_name: execution_time

migrations_paths:
    'DoctrineMigrations\Invoice': migrations/Invoice

em: invoice
