order_controllers:
    resource: ../src/Order/Infrastructure/Http/Controller/
    type: attribute

invoice_controllers:
    resource: ../src/Invoice/Infrastructure/Http/Controller/
    type: attribute

shared_controllers:
    resource: ../src/Shared/Infrastructure/Http/Controller/
    type: attribute
