name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          targets: php
          files: |
            compose.yaml
            compose.ci.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: docker compose -f compose.yaml -f compose.ci.yaml up -d --no-build
      -
        name: 🔍 Show Docker ps
        run: docker ps -a

      - name: 🔍 Inspect php container health
        run: docker inspect symfony-ddd-ecommerce-microservices-php-1

      - name: 🔍 Show PHP container logs
        run: docker logs symfony-ddd-ecommerce-microservices-php-1 || true

      - name: Debug port
        run: docker compose -f compose.yaml -f compose.ci.yaml port php 80

      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body --location http://localhost/health
      -
        name: Check HTTPS reachability
        if: false # Remove this line when the homepage will be configured, or change the path to check
        run: curl -vk --fail-with-body https://localhost
      -
        name: Check Mercure reachability
        run: curl -vkI --fail-with-body https://localhost/.well-known/mercure?topic=test
      -
        name: Create test database
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console -e test doctrine:database:create
      -
        name: Run migrations
        run: |
          docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console -e test doctrine:migrations:execute --up 'DoctrineMigrations\\Order\\Version20250708110539'
          docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      -
        name: Run PHPUnit
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/phpunit
      -
        name: Doctrine Schema Validator
        run: docker compose -f compose.yaml -f compose.ci.yaml exec -T php bin/console -e test doctrine:schema:validate
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
